In [161]:
import torch

In [162]:
words = open('names.txt', 'r').read().splitlines()
words[:4]

['emma', 'olivia', 'ava', 'isabella']

In [163]:
for word in words[:3]:
    chs = ['.'] + list(word) + ['.']
    for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
        print(ch1, ch2, ch3)

. e m
e m m
m m a
m a .
. o l
o l i
l i v
i v i
v i a
i a .
. a v
a v a
v a .


In [164]:
characters = sorted(list(set(''.join(words))))
stoi = {s: i+1 for i, s in enumerate(characters)}
stoi["."] = 0
itos = {i: s for s, i in stoi.items()}
stoi, itos

({'a': 1,
  'b': 2,
  'c': 3,
  'd': 4,
  'e': 5,
  'f': 6,
  'g': 7,
  'h': 8,
  'i': 9,
  'j': 10,
  'k': 11,
  'l': 12,
  'm': 13,
  'n': 14,
  'o': 15,
  'p': 16,
  'q': 17,
  'r': 18,
  's': 19,
  't': 20,
  'u': 21,
  'v': 22,
  'w': 23,
  'x': 24,
  'y': 25,
  'z': 26,
  '.': 0},
 {1: 'a',
  2: 'b',
  3: 'c',
  4: 'd',
  5: 'e',
  6: 'f',
  7: 'g',
  8: 'h',
  9: 'i',
  10: 'j',
  11: 'k',
  12: 'l',
  13: 'm',
  14: 'n',
  15: 'o',
  16: 'p',
  17: 'q',
  18: 'r',
  19: 's',
  20: 't',
  21: 'u',
  22: 'v',
  23: 'w',
  24: 'x',
  25: 'y',
  26: 'z',
  0: '.'})

In [165]:
N = torch.zeros((27, 27, 27), dtype=torch.int32)

In [166]:
for word in words:
    chs = ['.'] + list(word) + ['.']
    for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
        idx1 = stoi[ch1]
        idx2 = stoi[ch2]
        idx3 = stoi[ch3]
        N[idx1, idx2, idx3] += 1
N

tensor([[[  0,   0,   0,  ...,   0,   0,   0],
         [  0, 207, 190,  ...,  27, 173, 152],
         [  0, 169,   0,  ...,   0,   4,   0],
         ...,
         [  0,  57,   0,  ...,   1,  17,  11],
         [  0, 246,   0,  ...,   0,   0,   2],
         [  0, 456,   0,  ...,   0,  91,   1]],

        [[  0,   0,   0,  ...,   0,   0,   0],
         [ 40,   0,   5,  ...,   0,  20,  11],
         [ 36,  28,  20,  ...,   0,  12,   0],
         ...,
         [ 11,   5,   0,  ...,  17,   6,   3],
         [163, 389,  13,  ...,   0,  16,  40],
         [ 38, 123,   0,  ...,   0,  12,  22]],

        [[  0,   0,   0,  ...,   0,   0,   0],
         [ 46,   5,   5,  ...,   4,  31,   4],
         [  1,   8,   0,  ...,   0,   9,   0],
         ...,
         [  0,   0,   0,  ...,   0,   0,   0],
         [ 55,   4,   1,  ...,   0,   0,   0],
         [  0,   0,   0,  ...,   0,   0,   0]],

        ...,

        [[  0,   0,   0,  ...,   0,   0,   0],
         [ 10,   0,   2,  ...,   0,  10,   0]

In [167]:
g = torch.Generator().manual_seed(42)
P = (N+1).float()
P /= P.sum(2, keepdim=True)
P[0, 0]

tensor([0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370,
        0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370,
        0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370, 0.0370])

In [168]:
ex_idx = torch.multinomial(P[1, 1], 4, generator=g)
selection = [itos[i.item()] for i in ex_idx]
selection

['y', 'l', '.', 'm']

In [169]:

for i in range(10):
    out = []
    ix1 = 0
    ix2 = torch.randint(0, 27, (1,), generator=g).item()
    out.extend([ix1, ix2])
    while True:
        index = torch.multinomial(
            P[ix1, ix2], num_samples=1, replacement=True, generator=g).item()
        out.append(index)
        if index == 0:
            break
        ix1 = ix2
        ix2 = index
    # print(out)
    name = [itos[i] for i in out]
    print(''.join(name))

.wesmahle.
.man.
.roxgkthmang.
.kyn.
.layahd.
.neen.
.ana.
.na.
.brii.
.yah.


In [170]:
# computiing the overall likelihood of the dataset
log_likelihood = 0.0
n = 0

for word in words:
    chs = "." + word+"."
    for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
        idx1, idx2, idx3 = stoi[ch1], stoi[ch2], stoi[ch3]
        log_prob = torch.log(P[idx1, idx2, idx3])
        log_likelihood += log_prob
        n += 1

print(log_likelihood)
print(n)
print(-log_likelihood/n)

tensor(-410414.9688)
196113
tensor(2.0927)


### neuralnet

In [171]:
# exemple of probabilities of next letters for the character 0(.) and 1(a)
P[0, 1]

tensor([0.0002, 0.0469, 0.0430, 0.0072, 0.0827, 0.0126, 0.0050, 0.0041, 0.0207,
        0.0349, 0.0063, 0.0171, 0.1427, 0.0868, 0.1406, 0.0025, 0.0041, 0.0023,
        0.1089, 0.0439, 0.0165, 0.0345, 0.0550, 0.0016, 0.0063, 0.0392, 0.0345])

In [172]:
xs, ys = [], []

for word in words[:2]:
    chs = '.' + word + '.'
    for ch1, ch2, ch3 in zip(chs, chs[1:], chs[3:]):
        idx1, idx2, idx3 = stoi[ch1], stoi[ch2], stoi[ch3]
        xs.append([idx1, idx2])
        ys.append(idx3)


xs, ys = torch.tensor(xs), torch.tensor(ys)
num = xs.nelement()
W = torch.rand((27*2, 27), generator=g, requires_grad=True)
ys.shape[0]
xs

tensor([[ 0,  5],
        [ 5, 13],
        [13, 13],
        [ 0, 15],
        [15, 12],
        [12,  9],
        [ 9, 22],
        [22,  9]])

In [173]:
from torch.nn import functional as F
for i in range(10):
    xenc = F.one_hot(xs, num_classes=27).float()
    print(xenc.shape)
    logits = xenc@W
    counts = torch.exp(logits)
    probs = counts/counts.sum(dim=2, keepdim=True)
    break
    loss = -probs[torch.arange(num), torch.arange(num), ys]

torch.Size([8, 2, 27])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x27 and 54x27)