In [35]:
import tensorflow as tf
import random

In [36]:
words = open('../names.txt').read().split()

In [37]:
stoi = {s: i+1 for i, s in enumerate(sorted(set(''.join(words))))}
stoi['.'] = 0
itos = {s: i for i, s in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [38]:
tf.random.set_global_generator(42)
w = tf.Variable(tf.random.normal((3, 2)), name='w')
a = tf.Variable(tf.random.normal((2, 3)), name='a')
a@w

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.32033497,  0.06176215],
       [ 1.8183279 ,  0.91623193]], dtype=float32)>

In [47]:

def build_dataset(words: list[str]):
    X, Y = [], []
    context_size = 3
    for w in words:
        context = [0] * context_size
        for ch in w + ".":
            X.append(context)
            Y.append(stoi[ch])
            # output = [itos[i] for i in context]
            # print(f"{''.join(output)} ----> {ch}")
            context = context[1:] + [stoi[ch]]
    return tf.Variable(X), tf.Variable(Y)


n1, n2 = int(0.8 * len(words)), int(0.9 * len(words))
random.shuffle(words)

X_train, Y_train = build_dataset(words=words[:n1])
X_dev, Y_dev = build_dataset(words=words[n1:n2])
X_test, Y_test = build_dataset(words=words[n2:])

# X_train, Y_train = X_train.to(device=device), Y_train.to(device=device)
# X_dev, Y_dev = X_dev.to(device=device), Y_dev.to(device=device)
# X_test, Y_test = X_test.to(device=device), Y_test.to(device=device)

X_train.shape, X_dev.shape, Y_dev.shape

(TensorShape([182663, 3]), TensorShape([22684, 3]), TensorShape([22684]))

In [40]:
C = tf.Variable(tf.random.uniform(shape=(27, 5)), trainable=True)
W1 = tf.Variable(tf.random.uniform(shape=(15, 200)), trainable=True)
b1 = tf.Variable(tf.random.uniform(shape=(200,)), trainable=True)
W2 = tf.Variable(tf.random.uniform(shape=(200, 27)), trainable=True)
b2 = tf.Variable(tf.random.uniform(shape=(27,)), trainable=True)
parameters = [C, W1, b1, W2, b2]

In [41]:
ll = tf.gather(C, X_train)
tf.reshape(ll[0], shape=(-1, 15))

<tf.Tensor: shape=(1, 15), dtype=float32, numpy=
array([[0.41601348, 0.01093221, 0.46235168, 0.25209248, 0.91174185,
        0.41601348, 0.01093221, 0.46235168, 0.25209248, 0.91174185,
        0.41601348, 0.01093221, 0.46235168, 0.25209248, 0.91174185]],
      dtype=float32)>

In [42]:
sum(tf.size(p) for p in parameters)

<tf.Tensor: shape=(), dtype=int32, numpy=8762>

In [43]:

def forward(inputs):
    emb = tf.gather(C, inputs)
    h = tf.tanh(tf.reshape(emb, shape=(-1, 3*5)) @ W1+b1)
    logits = h@W2+b2
    return logits

In [44]:
stepi, lossi, lossd = [], [], []
ix = tf.random.uniform(shape=(32,), minval=0, maxval=26, dtype=tf.int32)
# print(ix)
print(tf.gather(X_train, ix).shape)

(32, 3)


In [ ]:
cross_entropy = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

n_iter = 2
for i in range(n_iter):

    # minibatch
    ix = tf.random.uniform(shape=(32,), minval=0,
                           maxval=X_train.shape[0], dtype=tf.int32)
    inputs = tf.gather(X_train, ix)
    targets = tf.gather(Y_train, ix)

    with tf.GradientTape() as tape:
        logits = forward(inputs)
        loss_train = cross_entropy(targets, logits).numpy()

        logits_dev = forward(X_dev)
        print(logits_dev.shape)
        print(logits_dev.shape)
        loss_dev = cross_entropy(X_dev, logits_dev).numpy()

    if i % 10 == 0:
        print(
            f"step {i}  train loss: {loss_train:.4f}  dev loss: {loss_dev:.4f}")

    gradients = tape.gradient(loss_train, parameters)
    lr = 0.1
    for p, g in zip(parameters, gradients):
        p = p - lr * g

    stepi.append(i)
    lossi.append(tf.math.log(loss_train).numpy())
    lossd.append(tf.math.log(loss_dev).numpy())

ValueError: `labels.shape` must equal `logits.shape` except for the last dimension. Received: labels.shape=(68238,) and logits.shape=(22746, 27)